spring:
  application:
    name: testsecu

  # H2 ?????? ?? (???)
  h2:
    console:
      enabled: true # H2 ?? ???
      path: /h2-console # H2 ?? ?? ??
  datasource:
    driver-class-name: org.h2.Driver # H2 ????
    url: jdbc:h2:mem:testdb # ???? DB ??, DB ??? testdb
    username: sa
    password:

  # MySQL ?? (???)
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/[db??]
  #    username:
  #    password:
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # ?????? ?? ? DB ???? ???? ????, ?? ? ??
      ddl-auto: create-drop
    # JPA? ???? SQL ??? ??? ???
    show-sql: true
    properties:
      hibernate:
        # H2 ??????? ?? SQL ??? ????? ??
        dialect: org.hibernate.dialect.H2Dialect
        # SQL ??? ??? ???? ???
        format_sql: true

server:
  port: 8080